### ISSUE TITLE
pipenv install : pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'monitori'": Expected stringEnd

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/automating-livestream-video-monitoring#30]
I git clone the forked repo on a Cloud 9 instance

I have a strange issue and I don't understand where is the issue

```
Admin:~/environment/automating-livestream-video-monitoring/broadcast-monitoring (main) $ pipenv install
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies...
Building requirements...
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 10), (line:1, col:11)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/cli/command.py", line 215, in install
    site_packages=state.site_packages
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/core.py", line 2008, in do_install
    keep_outdated=keep_outdated
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/core.py", line 1258, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/core.py", line 1068, in do_lock
    keep_outdated=keep_outdated
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/utils.py", line 1315, in venv_resolve_deps
    deps, project, r=False, include_index=True
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/utils.py", line 1447, in convert_deps_to_pip
    new_dep = Requirement.from_pipfile(dep_name, dep)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2745, in from_pipfile
    r = FileRequirement.from_pipfile(name, pipfile)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1842, in from_pipfile
    arg_dict["setup_info"] = arg_dict["parsed_line"].setup_info
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 806, in setup_info
    self.setup_info = self.get_setup_info()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 795, in get_setup_info
    setup_info = SetupInfo.from_ireq(self.ireq, subdir=self.subdirectory)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 772, in ireq
    self.parse_ireq()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 936, in parse_ireq
    if self.requirement is not None and self._ireq.req is None:
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 474, in requirement
    self.parse_requirement()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1082, in parse_requirement
    self._requirement = init_requirement(name)  # type: PackagingRequirement
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/utils.py", line 197, in init_requirement
    req = Requirement.parse(name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3153, in parse
    req, = parse_requirements(s)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3098, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc : e.loc + 8], e.msg
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'monitori'": Expected stringEnd
```

**Comment by gmarchand** [comment]
I delete this line https://github.com/aws-samples/automating-livestream-video-monitoring/blob/main/broadcast-monitoring/Pipfile#L18 and the install works without this package

**Comment by gmarchand** [comment]
I found a "fix" 

I cleaned this file https://github.com/aws-samples/automating-livestream-video-monitoring/blob/main/broadcast-monitoring/src/sharedlib/setup.py

```
setuptools.setup(
    name="Broadcast Monitoring Lambda Helpers",
    version="0.0.1",
    description="Helper classes",
    long_description="Helper classes",
    long_description_content_type="text/markdown",
    packages=setuptools.find_packages(),
    install_requires=[
        'boto3',
        'PyYAML'
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: Other/Proprietary License",
        "Operating System :: OS Independent",
    ],
)
```
